### ISSUE TITLE
Diagnosing install on ER-X v1.10.11

### ISSUE THREAD

**Issue by cr08** [bdwilson/vnstat-edgerouter#1]
Came across this repo recently and wanted to give it a go on my ER-X running firmware v1.10.11

Ran the instructions exactly and the run script seemed to complete successfully. I now have access to the dashboard under `/media/stat/` however after over a week of having it installed the images on the dashboard are still broken and do not display. Also if I try to run vnstat from the console it says there's no databases but I am unsure if this is even related (ie: If this script is storing the db somewhere else).

Any ideas what I can check/debug or is it possible the ER-X at this firmware level won't work?

**Comment by bdwilson** [comment]
Can you login as admin, sudo su -, then run this? vnstat -u -i eth0

If this works, I'll need to add an if statement within restore.sh to make sure to create the database if it doesn't exist.

**Comment by cr08** [comment]
This is what it returned for me

> root@ubnt:~# vnstat -u -i eth0
> Error: Unable to read database "/var/log/vnstat/eth0".
> Info: -> A new database has been created.

EDIT: And now it looks like the images show immediately on the stat page. Now just to wait for data to populate I guess?

**Comment by bubbaiOS** [comment]
Yep. Let me know if they show up.

**Comment by bdwilson** [comment]
> This is what it returned for me
> 
> > root@ubnt:~# vnstat -u -i eth0
> > Error: Unable to read database "/var/log/vnstat/eth0".
> > Info: -> A new database has been created.
> 
> EDIT: And now it looks like the images show immediately on the stat page. Now just to wait for data to populate I guess?

Yes let me know if he stays show up.

**Comment by cr08** [comment]
Apologies for the long delay on the reply. All seems good now. Data did start showing up within a day or two and seems to be progressing normally. ty for this!
