### ISSUE TITLE
Configure other than eth0 for display

### ISSUE THREAD

**Issue by eohrnberger** [bdwilson/vnstat-edgerouter#2]
I have an EdgeRouter X.  Installed successfully, and is presenting data.

However, I need to collect bandwidth consumption information for my Internet connection which happens to be on eth2.

Is there a config setting where I can make eth2 bandwidth to be reported?

Thanks,
    Erik.

**Comment by bubbaiOS** [comment]
Grab the repo and do a manual install (step 4). Before you do that edit the scripts and vnstat.conf and replace all instances of "eth0" with "eth2"

**Comment by eohrnberger** [comment]
Hi, figured it out.

Login to the router and su to root.

cd /var/www/htdocs/media/stat/cgi-bin

Edit the vnstati-update.sh, changing the indicated ethx interface you want to monitor.

You can check it by using the command line:
vnstat  -i ethx
